#!/bin/bash
openmm_dir=/home/software/openmm/openmm-7.3.1
conda_dir=/home/software/openmm//miniconda2-centos
export LD_LIBRARY_PATH=${openmm_dir}/lib:${openmm_dir}/lib/plugins:$LD_LIBRARY_PATH
${conda_dir}/bin/python $1 $2
