#!/bin/bash
openmm_dir=/projects2/insite/rajat.pal/software/openmm_7.5.0_atm_standalone/build/openmm_7.5.0
export PATH=/projects2/insite/rajat.pal/anaconda3/envs/openmm-env/bin:$PATH
export OPENMM_PLUGIN_DIR=${openmm_dir}/lib/plugins
export LD_LIBRARY_PATH=${openmm_dir}/lib:${openmm_dir}/lib/plugins:$LD_LIBRARY_PATH
export PYTHONPATH=${openmm_dir}/lib/python3.7/site-packages:$PYTHONPATH
python "$@"
