#!/bin/bash
# OPENMM_DIR should probably point to your CONDA environment
# export OPENMM_DIR=$HOME/miniconda3/envs/atm 
openmm_dir=$OPENMM_DIR
export OPENMM_PLUGIN_DIR=${openmm_dir}/lib/plugins
export LD_LIBRARY_PATH=${openmm_dir}/lib:${openmm_dir}/lib/plugins:$LD_LIBRARY_PATH
python "$@"
