name: Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: ../deploy-env

      - name: Build PyPI 📦
        run: |
          pip install build
          python -m build --sdist --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PUBLIC_PYPI_API_TOKEN }}
          skip_existing: true
