name: Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    timeout-minutes: 45
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "macos-13", "windows-2019"]
        python-version: ["3.11"] #, "3.9", "3.11", "3.12"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Lint with flake8
        run: |
          pip install flake8 coverage pytest-cov pytest pytest-subtests
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install pip deps
        run: |
          conda install ambertools -c conda-forge
          pip install pyyaml numpy pandas openmm-unofficial-cpu scipy cachetools xmltodict rdkit python-constraint validators networkx pydantic lxml
          pip install git+https://github.com/openforcefield/openff-utilities
          pip install git+https://github.com/openforcefield/openff-toolkit
          pip install git+https://github.com/openforcefield/openff-units
          pip install git+https://github.com/openforcefield/openff-forcefields
          pip install git+https://github.com/openforcefield/openff-interchange
          pip install git+https://github.com/openmm/openmmforcefields

      - name: Install package
        run: |
          pip install .

      - name: List conda environment
        run: conda list

      - name: Test
        run: |
          pytest ./tests
